### ISSUE TITLE
Exclude a route with uuid v4

### ISSUE THREAD

**Issue by carlocorradini** [jfromaniello/express-unless#29]
I need help to exclude from a _JWT_ protected route the path to **/api/v1/auth/verify/:uuid** where _:uuid_ is a UUID v4.
I've  tried different regex from [StackOverflow](https://stackoverflow.com/questions/136505/searching-for-uuids-in-text-with-regex) but none worked.

Here is my code:

```typescript
import { Router } from 'express';
import jwt from 'express-jwt';
import config from '@app/config';
import auth from './auth';

const router = Router();

router.use(
  '/auth',
  jwt({
    secret: config.SECURITY.JWT.SECRET,
  }).unless({
    path: [
      {
        url: '/api/v1/auth/verify/:uuid',
        methods: ['POST'],
      }
    ],
  }),
  auth
);
```

Thanks in advance.

**Comment by aiveneh** [comment]
https://github.com/jfromaniello/express-unless/issues/19#issuecomment-285142465

You would need to use Regex 
example - ` { url: /\/v1\/stores\/domain/i, methods: ['GET'] },`

**Comment by carlocorradini** [comment]
@aiveneh Unfortunately I can't.I have to exclude only that specific endpoint with a Regex for UUID v4.
I tried many Regex but none worked.
Can you help me:disappointed_relieved:?
Thanks:persevere:

**Comment by aiveneh** [comment]
Try this regex

` { url: /\/api\/v1\/auth\/verify/i, methods: ['GET'] } `
