### ISSUE TITLE
Possible "custom" option missing ?

### ISSUE THREAD

**Issue by TitaneBoy** [jfromaniello/express-unless#35]
Hi there. Since the last released version of express-unless (2.1.0), it seems that the "custom" option is missing in the package. At least, the "custom" option seems to be missing in the "Type definition" of the package

![image](https://user-images.githubusercontent.com/15614466/171731019-89a19a5e-0114-436a-899b-4b19f940030b.png)

![image](https://user-images.githubusercontent.com/15614466/171730887-a4389d5d-197c-4e84-a969-fdb96b7b3847.png)

Also, the documentation seems to say that this option must be available

![image](https://user-images.githubusercontent.com/15614466/171731303-1ac14bdb-34bd-4220-99ee-62f6d0e7f464.png)

Thank you for your help

**Comment by jfromaniello** [comment]
Fixed in `v2.1.1`. Thanks for reporting this

**Comment by jarvisuser9** [comment]
> Fixed in `v2.1.1`. Thanks for reporting this

Thanks! I'll look out for when it gets released to NPM.

**Comment by TitaneBoy** [comment]
@jfromaniello : Thanks a lot for the fix.
But unless I am missing something, it looks that version v2.1.1 is not yet published in npm, but it is tagged in github. Is it possible you've forget to publish this version or there is a reason why it is not yet published in npm ? 

Thanks in advance

**Comment by jfromaniello** [comment]
sorry about that, it is published now. Thanks for the heads up
