### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by KrisLau** [jfromaniello/express-unless#36]
Where is the changelog?

**Comment by jfromaniello** [comment]
As far as I remember this library never had a changelog. 

Do you think it is really important in a project like this?

Most of my libraries are very specific and have a clear purpose, so I am not sure is worth the time and effort. For some libraries I've used an script to autogenerate the changelog file from commits but this one has only ~40 commits.

**Comment by KrisLau** [comment]
@jfromaniello I asked mainly because I noticed I'm on v1.0.0 and the package is on 2.1.0 and I thought I had just missed seeing it somewhere. I might have worded the issue wrongly haha but I was looking for it rather than requesting one be made. 

If there aren't any breaking changes I'm quite fine without but I just wasn't sure if I should upgrade the package without knowing if there was anything I needed to be worried about.

**Comment by KrisLau** [comment]
@jfromaniello i upgraded to `v2.1.1` and that seems to cause my node backend to crash with the error:
```
decodeIDToken.unless is not a function
    at Object.<anonymous> (/Users/newuser/Desktop/Prototype/backend/index.js:57:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

Code: 
```
// Server side auth
app.use(decodeIDToken.unless({
    path: [
        '/test-connection',
        '/debug-sentry',
        /\/calendars/
    ]
}));
```

**Comment by jfromaniello** [comment]
This might be related to the fact that in v2, the export is different.. So you have to use:

```js
var { unless } = require("express-unless");
```

There have not been big chances between v1 and v2... only that I rewrote the code in typescript. The test suite is the same.

**Comment by KrisLau** [comment]
@jfromaniello what about for authoring middleware? currently my code is:
```
decodeIDToken.unless = require("express-unless");
```

**Comment by KrisLau** [comment]
ok I figured it out:
```
var { unless } = require("express-unless");
...
decodeIDToken.unless = unless;
```

**Comment by jfromaniello** [comment]
thanks for the heads up, you are right! I found the issue in the docs. 🙏🏽

**Comment by KrisLau** [comment]
~@jfromaniello No worries i made a pull request https://github.com/jfromaniello/express-unless/pull/37~ Oops just saw your change

**Comment by jfromaniello** [comment]
ohh thanks, and sorry !!!
