### ISSUE TITLE
How can I use RegExp?

### ISSUE THREAD

**Issue by burakkilic** [jfromaniello/express-unless#7]
Hi;

I tried to use RegExp like

    .unless({
        path: ['/auth/login', '/auth/signup', '^\/auth\/reset\/[A-Za-z0-9-_]*']
    }))

to let /auth/reset/46b957ea7272a916f5d71e79d7fde7dab7a91414

but it is not allowed. How can I do that?

**Comment by MarkusPint** [comment]
Remove the ' ' from around the RegExp. Right now your RegExp is being read as a string.

**Comment by burakkilic** [comment]
Thank you.
